### ISSUE TITLE
error while open battle1.snm

### ISSUE THREAD

**Issue by luca2125** [JeremyAnsel/XwaSnmConverter#1]
Hi,

I get this error while open battle1.snm:

![error_while_convert](https://user-images.githubusercontent.com/55355625/81594793-c1589280-93c1-11ea-8f83-c71e6f66f99a.png)

is possible solve the problem ?

**Comment by Choum28** [comment]
Same problem for Battle1 and also the INTRO_FINAL.SNM
![image](https://github.com/user-attachments/assets/0e56dfbf-bfec-4fa4-bf5e-fba14578fe73)

**Comment by JeremyAnsel** [comment]
Hello,
Which version of the tool do you use?
Is there an error with the latest version?
https://github.com/JeremyAnsel/XwaSnmConverter/releases/latest

**Comment by luca2125** [comment]
I don't remember to be honest was passed 4 years.

There is a possibility perhaps that this problem in the meantime may have already been solved.

**Comment by Choum28** [comment]
I tried today the lastest version on a french Vanilla game, all SNP file can be converted without errors.
